apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sspl-flask-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "sspl-flask-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "sspl-flask-app.name" . }}
    spec:
      serviceAccountName: {{ include "sspl-flask-app.serviceAccountName" . }}
      containers:
        - name: flask-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: log-volume
              mountPath: {{ .Values.persistence.mountPath }}
          livenessProbe: {{ toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe: {{ toYaml .Values.readinessProbe | nindent 12 }}
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: {{ include "sspl-flask-app.fullname" . }}-logs
