{{- if and .Values.serviceAccount (or (hasKey .Values.serviceAccount "create") (hasKey .Values.serviceAccount "automount")) }}
  {{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sspl-flask-app.serviceAccountName" . }}
  labels:
    {{- include "sspl-flask-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ default true .Values.serviceAccount.automount }}
  {{- end }}
{{- end }}
