replicaCount: 2

image:
  repository: hariprotonmail/sspl_py_tools_web
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 5000

serviceAccount:
  create: true
  name: ""
  automount: true
  annotations: {}

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: sspl.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  mountPath: /app/logs

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  